### ISSUE TITLE
A `mock` field is created when `simd init`

### ISSUE THREAD

**Issue by zemyblue** [line/lbm-sdk#770]
## Summary of Bug

A `mock` field is created in `app_state` when `simd init`

`mock` is not module, but the field is added. 

```json
{
  "chain_id": "simd-testing",
  "consensus_params": {},
  "app_state": {
…
    "mint": {...},
    "mock": null,
    "params": null,
...
  }
}
```

## Version

lbm-sdk v0.46.0-rc9

## Steps to Reproduce

____

## For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [ ] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by dudong2** [comment]
At #651, the ibcmock module was included in the module initialization and begin block, end blocker, init genesis order.
So ,there was a bug in genesis.json including the ibcmock.

Here, I tried to remove ibcmock, but this has proven to be impossible currently.

If you look at the structure of cosmos, cosmos-sdk and ibc-go are separated from each other. And these are combined and distributed in the form of gaia. 
So, cosmos-sdk doesn't need any import for ibc.

However, the structure of lbm includes ibc as a module in lbm-sdk. 
Therefore, when creating a simapp, ibcmock must also be included as a module. 
Because lbm doesn't need to include ibcmock, I decide it's not an issue and close.
