### ISSUE TITLE
bump up to cosmos-sdk v0.45.10

### ISSUE THREAD

**Issue by zemyblue** [line/lbm-sdk#775]
## Summary

bump up to cosmos-sdk v0.45.10
https://github.com/cosmos/cosmos-sdk/releases/tag/v0.45.10

## Proposal

____

#### For Admin Use

- [x] Not duplicate issue
- [x] Appropriate labels applied
- [x] Appropriate contributors tagged
- [x] Contributor assigned/self-assigned

**Comment by dudong2** [comment]
From https://github.com/line/lbm-sdk/pull/441, map was changed to sync.Map. Since these functions are no longer managed, it is difficult to bump up with the changes in the code of cosmos-sdk. I did a performance test to see if I could actually revert it.

```go
type Store struct {
	mtx           sync.RWMutex
	cache         sync.Map
	deleted       sync.Map
	unsortedCache sync.Map
	sortedCache   *dbm.MemDB // always ascending sorted
	parent        types.KVStore
}

type Store struct {
	mtx           sync.Mutex
	cache         map[string]*cValue
	deleted       map[string]struct{}
	unsortedCache map[string]struct{}
	sortedCache   *dbm.MemDB // always ascending sorted
	parent        types.KVStore
}
```

```
machine spec: 3.3GHz 6core Inter Core i5 / 16GB DDR4
Sync.Map: 1845 tps
map: 1872 tps
```

When I reverted to the code in cosmos-sdk, the tps came out a bit high. So I decided to revert it.

**Comment by dudong2** [comment]
From https://github.com/cosmos/cosmos-sdk/pull/13540, there is no additional issue about changing the default value of iavlDisablefastNode to true. 
I could not found any issues in terms of functionality and performance, so I decided to apply that pr as is.
